models:
  gpt2:
    name: gpt2
    url: http://localhost:8001
    device: cuda
    priority: 1
  qwen:
    name: Qwen/Qwen2.5-0.5B-Instruct
    url: http://localhost:8002
    device: cpu
    VLLM_CPU_OMP_THREADS_BIND: 1
    VLLM_CPU_KVCACHE_SPACE: 1
  llama:
    name: meta-llama/Llama-3.2-1B-Instruct
    url: http://localhost:8003
    device: cpu
    VLLM_CPU_OMP_THREADS_BIND: 2
    VLLM_CPU_KVCACHE_SPACE: 1